version: "2"
services:
   moodle-moosh-docker-app:
     build:
      context: PHP/
      dockerfile: PHP.Dockerfile
     restart: always
     container_name: moodle-moosh-docker-app
     volumes:
       - ./moodle:/var/www/html
       - ./moodledata:/var/www/moodledata
       - ./conf/local.ini:/usr/local/etc/php/php.ini
     networks:
       - traefik-global-proxy
       - moodle-moosh-docker_default
     depends_on:
       - moodle-moosh-docker-db
   moodle-moosh-docker-moosh:
     build:
      context: moosh_docker/  
      dockerfile: moosh.Dockerfile
     restart: always
     container_name: moodle-moosh-docker-moosh
     volumes_from:
       - moodle-moosh-docker-app
     volumes:
       - ./moosh:/var/www/moosh
       - ./shared:/var/www/shared
     networks:
       - traefik-global-proxy
       - moodle-moosh-docker_default
     depends_on:
       - moodle-moosh-docker-app
   moodle-moosh-docker-web:
     image: nginx
     restart: always
     container_name: moodle-moosh-docker-web
     volumes:
       - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
     volumes_from:
       - moodle-moosh-docker-app
    #  ports:
    #  - "8088:8088"
     labels:
        - "traefik.enable=true" # enables the service
        - "traefik.http.routers.moodlefull.rule=Host(`docker-moosh.localhost`)" # domain to expose on
        - "traefik.http.routers.moodlefull.entrypoints=web" # if you named your 443 entrypoint differently than webscure, substitute it here!
     networks:
       - traefik-global-proxy
       - moodle-moosh-docker_default
   moodle-moosh-docker-db:
     image: wodby/mariadb:10.6
     restart: always
     container_name: moodle-moosh-docker-db
     environment:
           - MYSQL_USER=moodleuser
           - MYSQL_PASSWORD=mysqlpassword  
           - MYSQL_DATABASE=moodle
           - MYSQL_ALLOW_EMPTY_PASSWORD=true
     volumes:
           - ./dbdata:/var/lib/mysql
           - ./conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
     expose:
           - "3306"
     networks:
           - moodle-moosh-docker_default
   moodle-moosh-docker-cron:
      container_name: moodle-moosh-docker-cron
      build:
        context: Cron/
        dockerfile: Cron.Dockerfile
      volumes_from:
        - moodle-moosh-docker-app 
      restart: always
      volumes:
        - ./log/cron:/var/log/cron
      networks:
        - traefik-global-proxy
        - moodle-moosh-docker_default
      depends_on:
        - moodle-moosh-docker-db
   moodle-moosh-docker-pma:
      container_name: moodle-moosh-docker-pma
      image: phpmyadmin/phpmyadmin
      restart: always
      # ports:
      #     - "8089:80"
      labels:
        - "traefik.enable=true" # enables the service
        - "traefik.http.routers.pmafull.rule=Host(`pma.moodle-moosh.localhost`)" # domain to expose on
        - "traefik.http.routers.pmafull.entrypoints=web" # if you named your 443 entrypoint differently than webscure, substitute it here!
      environment:
         PMA_HOST: moodle-moosh-docker-db
      networks:
          - traefik-global-proxy
          - moodle-moosh-docker_default
      depends_on:
         - moodle-moosh-docker-db
networks:
  traefik-global-proxy:
      external: true
  moodle-moosh-docker_default:
      external: false

